# Generated by Django 4.1.3 on 2022-11-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("courser", models.CharField(max_length=140)),
                ("rating", models.IntegerField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
