# Generated by Django 4.1.3 on 2022-12-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_userimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userImg",
            field=models.ImageField(default=1, upload_to="users"),
            preserve_default=False,
        ),
    ]
